# CM hardware
BOARD_HARDWARE_CLASS := $(LOCAL_PATH)/cmhw

# LightHAL
TARGET_PROVIDES_LIBLIGHT := true

# MTK Hardware
BOARD_USES_MTK_HARDWARE := true
BOARD_USE_SOFT_GATEKEEPER := true
BOARD_USES_LEGACY_MTK_AV_BLOB := true
BOARD_USES_MTK_AUDIO := true