# RIL
BOARD_CONNECTIVITY_VENDOR := MediaTek
BOARD_PROVIDES_RILD := true
BOARD_RIL_CLASS := ../../../device/infinix/x603/ril
MTK_IMS_SUPPORT = yes
MTK_MULTI_SIM_SUPPORT = dsds
MTK_SIM1_SOCKET_TYPE = 1
MTK_SIM2_SOCKET_TYPE = 1
MTK_SIM_HOT_SWAP = yes
MTK_SIM_HOT_SWAP_COMMON_SLOT = yes
MTK_SIM_RECOVERY = yes
MTK_SWCHR_SUPPORT = yes
MTK_VILTE_SUPPORT = yes